# .github/workflows/build-wheel.yml
name: Build and Upload Wheel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application
      run: |
        pip install -e .
        pytest .

    - name: Build package
      run: |
        python -m build --wheel

    - name: Upload wheel as artifact
      uses: actions/upload-artifact@v4
      with:
        name: blog
        path: dist/
